// Plain-text version of a Task 1 stimulus — what the examiner model reads when
// the chart is generated by the app rather than uploaded as an image.

import type { Visual } from "./tasks";

export function describeVisual(v: Visual): string {
  if (v.kind === "table") {
    return [v.columns.join(" | "), ...v.rows.map((r) => r.join(" | "))].join("\n");
  }
  if (v.kind === "pie") {
    return [
      `Pie charts (${v.unit}).`,
      ...v.groups.map((g) => `${g.label}: ${g.slices.map((sl) => `${sl.label} ${sl.value}%`).join(", ")}`),
    ].join("\n");
  }
  if (v.kind === "process") {
    return v.steps.map((s, i) => `${i + 1}. ${s.title}: ${s.detail}`).join("\n");
  }
  const header = `${v.kind === "line" ? "Line graph" : "Bar chart"} (${v.unit}). Columns: ${v.series.join(", ")}`;
  return [header, ...v.points.map((p) => `${p.label}: ${p.values.map((n, i) => `${v.series[i]} ${n}`).join(", ")}`)].join("\n");
}
